# Site Details
name: BEARly Speaking
description: Devdutt blogs about anything that intrigues him, not only in the coding world, but some...
tagline: 'Because we are coding!'
url: 'http://blog.devdutt.ga/'

# About Author is provided in _data/authors.yml

# Build Configuration
destination: _build
permalink: /:categories/:short_year-:month/:title/
exclude: []
include: []
incremental: true
rss: feed.xml
port: 9926

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Base URLs
baseurl: '/'
baseurl_img:   '/images/'
baseurl_featured_img: '/images/feature/'
baseurl_featured_thumbnail: '/images/thumb/'
baseurl_javascript: '/js/'
baseurl_css: '/css/'
