# Site Details
name: OMline
title: OMline
description: A theme for the students, the writers and many other people...
tagline: 'Because we are coding!'
url: 'http://devdutt.ga/OMline'

# About Author is provided in _data/authors.yml

# Build Configuration
destination: _build
permalink: /:categories/:short_year-:month/:title/
exclude: []
include: []
incremental: true
rss: feed.xml
port: 9926

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Base URLs
baseurl: '/'
baseurl_img:   '/images/'
baseurl_featured_img: '/images/feature/'
baseurl_featured_thumbnail: '/images/thumb/'
baseurl_javascript: '/js/'
baseurl_css: '/css/'

theme: jekyll-theme-OMline
